create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  details text not null default '',
  category text not null check (category in ('Frontend', 'Full-Stack')),
  tags text[] not null default array[]::text[],
  url text not null,
  github_url text not null default '',
  preview_image text not null default '',
  card_image_light text,
  card_image_dark text,
  featured boolean not null default false
);

alter table public.projects enable row level security;

drop policy if exists "Projects are publicly readable" on public.projects;
create policy "Projects are publicly readable"
  on public.projects
  for select
  to anon, authenticated
  using (true);

grant select on public.projects to anon, authenticated;
grant all on public.projects to service_role;
grant usage, select on sequence public.projects_id_seq to service_role;

create table if not exists public.website_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  phone text,
  website_type text,
  budget text,
  timeline text,
  description text,
  source text not null default 'contact_form',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

alter table public.website_inquiries add column if not exists name text;
alter table public.website_inquiries add column if not exists email text;
alter table public.website_inquiries add column if not exists message text;
alter table public.website_inquiries add column if not exists phone text;
alter table public.website_inquiries add column if not exists website_type text;
alter table public.website_inquiries add column if not exists budget text;
alter table public.website_inquiries add column if not exists timeline text;
alter table public.website_inquiries add column if not exists description text;
alter table public.website_inquiries add column if not exists source text not null default 'contact_form';
alter table public.website_inquiries add column if not exists status text not null default 'new';
alter table public.website_inquiries add column if not exists created_at timestamptz not null default now();

update public.website_inquiries
  set message = coalesce(description, '')
  where message is null;
alter table public.website_inquiries alter column message set not null;
alter table public.website_inquiries alter column phone drop not null;
alter table public.website_inquiries alter column website_type drop not null;
alter table public.website_inquiries alter column budget drop not null;
alter table public.website_inquiries alter column timeline drop not null;
alter table public.website_inquiries alter column description drop not null;

alter table public.website_inquiries enable row level security;

revoke all on public.website_inquiries from public, anon, authenticated;
grant all on public.website_inquiries to service_role;
create index if not exists website_inquiries_created_at_idx
  on public.website_inquiries (created_at desc);
